apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wellinkare-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: oauth.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth-ms-service
                port:
                  number: 2000
    - host: assessment.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assessment-ms-service
                port:
                  number: 8094
    - host: config-server.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: config-server-service
                port:
                  number: 2001
    - host: healthcare-facility.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: healthcare-facility-service
                port:
                  number: 8093
    - host: healthcare.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: healthcare-service
                port:
                  number: 8092
    - host: notifications.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8090