apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wellinkare-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: int.oauth.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth-ms-service-int
                port:
                  number: 2000
    - host: int.assessment.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assessment-ms-service-int
                port:
                  number: 8094
    - host: int.config-server.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: config-server-service-int
                port:
                  number: 2001
    - host: int.healthcare-facility.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: healthcare-facility-service-int
                port:
                  number: 8093
    - host: int.healthcare.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: healthcare-service-int
                port:
                  number: 8092
    - host: int.notifications.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notification-service-int
                port:
                  number: 8090