apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: 12011/config-server:second
        ports:
        - name: conf-port
          containerPort: 2001
        env:
          - name: spring.boot.admin.client.uri
            value: http://config-server-service-int:2003


