apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "config-server.selectorLabels" . | nindent 4 }}
