apiVersion: v1
kind: Service
metadata:
  name: {{ include "back-office.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "back-office.selectorLabels" . | nindent 4 }}