apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-facility-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-facility-ms
  template:
    metadata:
      labels:
        app: healthcare-facility-ms
    spec:
      containers:
      - name: healthcare-facility-ms
        image: 12011/healthcare-facility:latest
        ports:
        - name: healthfaci-port
          containerPort: 8093
        imagePullPolicy: Always
        env:
          - name: spring.cloud.config.uri
            value: http://config-server-service-dev:2001
          - name: spring.profiles.active
            value: dev