apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth-ms
  template:
    metadata:
      labels:
        app: oauth-ms
    spec:
      containers:
      - name: oauth-ms
        image: 12011/oauth:first
        ports:
        - name: oauth-ms-port
          containerPort: 2000
        imagePullPolicy: Always
        env:
          - name: spring.cloud.config.uri
            value: http://config-server-service:2001
          - name: spring.profiles.active
            value: local