apiVersion: v1
kind: Service
metadata:
  name: {{ include "healthcare-ms.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "healthcare-ms.selectorLabels" . | nindent 4 }}