apiVersion: v1
kind: Pod 
metadata:
  name: medical-db
  labels:
    app: medical-db
spec:
  containers:
  - name: postgresql
    image: postgres:latest
    ports:
    - name: postgres-port
      containerPort: 5432
    env:
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret 
            key: db-password

